version: "3"
services:
  db:
    # container_name is ignored in swarm and result in a clash when replicating service
    container_name: ashipa-mms-2.0.0-postgres-devel
    labels:
      ashipa-mms-2.0.0-psql-db-devel: "This the postgresql database"
    build:
      context: .
      dockerfile: psql/Dockerfile
    image: ashipa-mms-2.0.0-postgres-devel:1.0.0
    # deploy:
      # when considering 1+ replicas -> mount common data directory for all replicas and nginx for tcp & udp load balancing
      # mode: "replicated"
      # replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "5552:5432"
    volumes:
      - /var/lib/postgresql/ashipa-mms-v2/:/var/lib/postgresql/data

  backend:
  # can replicate backend and setup proxy to upstreams via nginx
    container_name: ashipa-mms-2.0.0-backend-devel
    labels:
      ashipa-mms-2.0.0-nodejs-backend-devel: "This the MMS backend"
    build:
      context: ./
      dockerfile: Dockerfile
    image: ashipa-mms-2.0.0-backend-devel:1.0.0
    restart: unless-stopped
    depends_on:
      - db
    network_mode: "bridge"
    links:
      - "db:database"
    ports:
      - "9090:9090"
    volumes:
      - ./dist:/usr/app

# volumes:
#   ashipa-mms-2.0.0-psql-devel-volume: