# TODO add frontend
version: "3"
services:
  db:
    container_name: siwes-db
    labels:
      siwes-db: "This the MongoDB Database"
    build:
      context: .
      dockerfile: mongodb/Dockerfile
    image: siwes-db:1.0.0
    restart: unless-stopped
    networks:
      - siwes-common-network
    ports:
      - "27100:27017"
    volumes:
      - ./mongodb:/home/mongodb
      - ./mongodb:/docker-entrypoint-initdb.d
      - ./mongodb/mongod.conf:/etc/mongod.conf:rw
      - $HOME/siwes-db:/data/db:rw
      # - /var/log/mongodb/mongod.log:/var/log/mongodb/mongod.log:rw
    command: ['--config', '/etc/mongod.conf']

  backend:
    container_name: siwes-backend
    labels:
      siwes-backend: "This the Backend"
    build:
      context: ./
      dockerfile: Dockerfile
    image: siwes-backend:1.0.0
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - siwes-common-network
    ports:
      - "9100:9100"
    volumes:
      - ./dist:/usr/app

networks:
  siwes-common-network:
    driver: bridge
